### ISSUE TITLE
KeyError on restart

### ISSUE THREAD

**Issue by antondalgren** [cloudamqp/avalanchemq#192]
When restarting avalanchemq we get a KeyError which results in the broker never starts and some data has to be wiped in order for the broker to come back up.

This only affects the broker if it has queues that has x-message-ttl

After some researching I've narrowed it down to the the issue is that an SP loaded from enq file reference a segment that doesn't exist anymore. It want to read from the segment to get metadata to find out if the message should be expired or not.

Still errors on KeyError on restart in `alpha.21`, now we handle the error but it should occur in the first place.

**Comment by carlhoerberg** [comment]
@snichme we fixed this, right?

**Comment by snichme** [comment]
Yes and no, I've still seen it occur on a restart but now we handle the it, by adding the SP to the ack file. 
Haven't investigated further which is why this issue isn't resolved yet, I would like to know why it happen in the first place.

**Comment by carlhoerberg** [comment]
What can we search for to find out when that happens? What do we log when
we put the SP in the ack file?

**Comment by carlhoerberg** [comment]
Are you sure it's always safe to do so?

**Comment by jage** [comment]
We've had a discussion and we'll close this for now. This "shouldn't happen" and we're in the process of rewriting segment handling.
